"use client";

import { useRouter } from "next/navigation";
import { Loader2, Sparkles } from "lucide-react";
import { useState, useTransition } from "react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import type { BuildPlan } from "@/domain/analysis";
import { generateBuildPlan } from "@/server/actions/ai";

/** "Build this experiment" — shows the cached AI plan or lets the viewer generate it once. */
export function BuildPlanSection({ experimentId, plan, aiAvailable }: { experimentId: string; plan: BuildPlan | null; aiAvailable: boolean }) {
  const router = useRouter();
  const [pending, start] = useTransition();
  const [error, setError] = useState<string | null>(null);

  if (!plan) {
    return (
      <Card className="flex flex-col items-start gap-3 border-dashed p-6">
        <p className="text-sm font-medium text-fg">Detailed build plan</p>
        <p className="max-w-xl text-sm text-fg-muted">
          {aiAvailable
            ? "Generate a milestone-by-milestone plan with a suggested repository layout, evaluation criteria and risks. It is generated once and saved for everyone."
            : "A detailed plan (milestones, repository layout, evaluation, risks) is generated by the AI provider. None is configured yet — the step-by-step outline above is the curated version."}
        </p>
        {aiAvailable && (
          <Button
            variant="accent"
            disabled={pending}
            onClick={() =>
              start(async () => {
                setError(null);
                const res = await generateBuildPlan(experimentId);
                if (res.ok) router.refresh();
                else setError(res.error ?? "Something went wrong");
              })
            }
          >
            {pending ? <Loader2 className="animate-spin" /> : <Sparkles />}
            {pending ? "Generating plan…" : "Generate complete build plan"}
          </Button>
        )}
        {error && <p className="text-sm text-down">{error}</p>}
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      <Card className="p-6">
        <p className="mb-1 font-mono text-[11px] uppercase tracking-wider text-analysis">AI-generated plan</p>
        <p className="text-[15px] leading-relaxed text-fg-muted">{plan.overview}</p>
      </Card>
      <ol className="space-y-3">
        {plan.milestones.map((m, i) => (
          <li key={m.title} className="rounded-[var(--radius-card)] border border-line bg-surface-1 p-5">
            <p className="font-mono text-[11px] uppercase tracking-wider text-fg-subtle">Milestone {i + 1}</p>
            <p className="mt-1 text-[15px] font-medium text-fg">{m.title}</p>
            <p className="mt-1 text-sm text-fg-muted">{m.outcome}</p>
            <ul className="mt-3 space-y-1.5">
              {m.tasks.map((t) => (
                <li key={t} className="flex gap-2 text-sm text-fg-muted">
                  <span className="mt-[7px] size-1.5 shrink-0 rounded-sm border border-line-strong" aria-hidden />
                  {t}
                </li>
              ))}
            </ul>
          </li>
        ))}
      </ol>
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
        {plan.repoStructure.length > 0 && (
          <Card className="p-5">
            <p className="mb-2 text-sm font-medium text-fg">Suggested repository layout</p>
            <ul className="space-y-1 font-mono text-[12.5px] text-fg-muted">
              {plan.repoStructure.map((r) => (
                <li key={r} className="break-words">
                  {r}
                </li>
              ))}
            </ul>
          </Card>
        )}
        <Card className="space-y-4 p-5">
          <List title="How to evaluate it" items={plan.evaluation} />
          <List title="Risks" items={plan.risks} />
          <List title="Stretch goals" items={plan.stretchGoals} />
        </Card>
      </div>
    </div>
  );
}

function List({ title, items }: { title: string; items: string[] }) {
  if (items.length === 0) return null;
  return (
    <div>
      <p className="mb-1.5 text-sm font-medium text-fg">{title}</p>
      <ul className="space-y-1 text-sm text-fg-muted">
        {items.map((i) => (
          <li key={i}>· {i}</li>
        ))}
      </ul>
    </div>
  );
}
